### ISSUE TITLE
implement logOut JButton

### ISSUE THREAD

**Issue by henryqin13** [henryqin13/CSC207-GP#76]
Right now clicking logOut does nothing, when it should redirect the users to the main Menu.

**Comment by solairamu** [comment]
I got it working where it takes the user back to the sign up page, after we implement the main menu, I can easily change one line of code to change from "sign Up" to "Main Menu" in order send back to main menu.

**Comment by solairamu** [comment]
WIth the addition of the main menu, this is now completely finished.
